### ISSUE TITLE
Clarification for example of "W" instruction in User Manual in "Addressing Modes"

### ISSUE THREAD

**Issue by bradgrantham** [slu4coder/Minimal-UART-CPU-System#2]
The "W" section "Addressing Modes" in the [User Manual](https://docs.google.com/document/d/1c2ZHtLd1BBAwcBAjBZZJmCA3AXpbpv80dlAtsMYpuF4/edit?usp=sharing) states `Example: LDI 255 ADW 0x04 0xf0 adds 10 the the content of 0xf004 and in the case of an overflow (carry flag set) also increases address 0xf005.`  But this looks like it adds *255* to the content of 0xf004.  Is that correct?

**Comment by slu4coder** [comment]
Hi Brad,

thanks for pointing this out. It is much appreciated. Sometimes after
midnight things start losing their shape... I've corrected this to:

‘W’indicates ‘to word at absolute address’ mode. Again the accumulator
provides the argument but the result is stored in the word at the
address following the opcode. Example: LDI 250 ADW 0x04 0xf0 adds 250 to
the content of 0xf004. In case of an overflow (carry flag set) the
content of 0xf005 automatically increments.

Cheers!
slu4

**Comment by bradgrantham** [comment]
> thanks for pointing this out. It is much appreciated. Sometimes after midnight things start losing their shape...

Yeah, they do sometimes.  :)

Great, thank you!
